### ISSUE TITLE
`libtinyexr-tests` package is missing

### ISSUE THREAD

**Issue by boris-kolpackov** [lyrahgames/build2-tinyexr#2]
You've submitted the `libtinyexr` package but not `libtinyexr-tests`.

BTW, you could have easily noticed this yourself if you checked the builds in the queue after your submission, they are all failing and the reason is pretty clear:

https://queue.cppget.org/libtinyexr/1.0.6

**Comment by lyrahgames** [comment]
I am sorry about that, but I already knew and wanted to note it and add an issue as soon as I would be back in the office. Unfortunately, the tests package could not be successfully published. It was rejected because it was too big. It is around 250 MiB and I didn't have an immediate fix. Sadly, the library package had been already submitted at that time.

**Comment by boris-kolpackov** [comment]
> It is around 250 MiB

No, please, don't submit it ;-) We need to substantially reduced this somehow.

I suspect these are some test input files. If it's just one or two large ones (common case), then I would just omit them. If it's a large number of small tests (less common case), then I guess we will just need to pick some sample/subset of them.

**Comment by lyrahgames** [comment]
> No, please, don't submit it ;-) We need to substantially reduced this somehow.

^^ Thought so. 

> I suspect these are some test input files. If it's just one or two large ones (common case), then I would just omit them. If it's a large number of small tests (less common case), then I guess we will just need to pick some sample/subset of them.

Indeed, the test data in the folder `libtinyexr-tests/data/` make up 240 MiB and consist of many `.exr` image files each of them only a few MiBs in size. So, we would need to use the second approach. The main problem is that all tests are part of the file `libtinyexr-tests/test/unit/tester.cc`.

I suggest to keep the `libtinyexr-tests` package as it is but remove the declaration as tests package inside `libtinyexr/manifest`. Instead, I can try to construct  another tests package, like `libtinyexr-small-tests`, that can be used for `cppget.org` but still keep the old functionality of `libtinyexr-tests` in the repository for more thorough testing. For `libtinyexr-small-tests`, I would use a copy-and-paste approach for some tests and some files to make its size smaller. By keeping `libtinyexr-tests`, the copy-and-paste would not be as error-prone as at least locally I could always check against the thorough tests.

What do you think?

**Comment by lyrahgames** [comment]
Maybe even better:
The `libtinyexr` package already provides some basic unit tests. Maybe we should only remove the tests declaration in the `manifest` and not provide another external tests package. I will leave `libtinyexr-tests` in the repository for the above reasons but will not publish it. For the CI runs, it can still be used.

**Comment by boris-kolpackov** [comment]
> The `libtinyexr` package already provides some basic unit tests. Maybe we should only remove the tests declaration in the `manifest` and not provide another external tests package.

Yes, sounds good to me!
